mcq/app/urls.py
from django.urls import path
from . import views
from . views import (CategoriesView,QuestionsView, PurchasesQuestionSets,
                     SliderListAPIview,PurchaseCreateAPIView, ExamList,
                     ScoreCreateAPIView, PaymentPatnerList,FreeQuestionList)

urlpatterns = [
    path('sliders', SliderListAPIview.as_view(), name='sliders'),
    path('category', CategoriesView.as_view(), name='categories'), #all category get
    path('category/<int:id>', CategoriesView.as_view(), name='categories'), # categorie related question sets
    path('questions_sets',QuestionsView.as_view(), name='questionsset'), # all question sets get
    path('questions_sets/<int:id>',QuestionsView.as_view(), name='questions'), # set related questions
    path('question_sets/purchase',PurchasesQuestionSets.as_view(), name='purchase_question_sets' ), #Purchase Question sets list
    path('question_sets/purchase/create', PurchaseCreateAPIView.as_view(), name='purchase_question_set'), # purchase question sets
    path('exam',ExamList.as_view(), name ='examlist'), #Free and Purchase question sets
    path('score',ScoreCreateAPIView.as_view(),name='score_create'),
    path('payment_method',PaymentPatnerList.as_view(), name='payment_method' ), # payment method
    path('free',FreeQuestionList.as_view(), name='free_question')
]

mcq/app2/urls.py
from django.urls import path
from . import views 
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from .views import *
# from .views import GetQuestionSetsView


app_name ='dashboard'
urlpatterns = [
        path('',views.index,name='index'),
        path('login/', views.login, name='login'),
        path('logout', views.userlogout, name='logout'),
        # path('question/<int:id>/',views.question,name='question'),
        # path('question-set/<str:question_set_slug>/', views.question_set_detail, name='question_set_detail'),
        path('question/<int:id>/', views.question, name='question'),
        path('question/delete', views.question_delete, name="question_delete"),
        path('subcategories', views.load_sub_category, name="ajax_load_courses"),

        path('slider/',views.slider,name='slider'),
        path('deleteSlider/<int:id>/',views.deleteSlider,name='deleteSlider'),

        path('add_Slider',views.add_edit_Slider,name='add_Slider'),
        path('edit_Slider/<int:id>/',views.add_edit_Slider,name='edit_Slider'),
        
        
        path('categorie',views.categorie,name='categorie'),
        path('category/<slug:slug>', views.category_related_sets, name='related_question_sets'),
        path('deleteCategories/<int:id>/',views.deleteCategories,name='deleteCategories'),

        path('add_Categories',views.add_edit_Categories,name='add_Categories'),
        path('edit_Categories/<int:id>/',views.add_edit_Categories,name='edit_Categories'),
        
        path('questionSets',views.questionSets,name='questionSets'),
        path('questionset/delete/<int:id>',views.deletequestionSets, name='delete_question_set'),
        path('deletequestionSets/<int:id>/',views.deletequestionSets,name='deletequestionSets'),

        path('add_QuestionSets',views.add_edit_QuestionSets,name='add_QuestionSets'),
        path('edit_QuestionSets/<int:id>/',views.add_edit_QuestionSets,name='edit_QuestionSets'),
        
        
        path('purchase_list/', views.purchase_list, name='purchases'),
        path('update_purchase_list/<int:id>/', views.update_purchase_list, name='update_purchase_list'),
        path('deletepurchases/<int:id>/',views.deletepurchases,name='deletepurchases'),

        path('add_question', views.add_question, name='add_question'),
        path('add_question/<int:setid>', views.add_question, name='addquestion'),
        path('add_question/update/<int:question_id>', views.add_question, name='update_question'),

        path('get_question_sets/', GetQuestionSetsView.as_view(), name='get_question_sets'),

        path('change_password/', views.change_password, name='change_password'),
        path('questions/', views.question, name='questions'),

        #testing
        path('test',views.add_question, name='test'),
        path('user/', views.user, name='user'),
        

        #question ajax
        path('get_question',views.get_question_details, name='get_question_details')


]+ static (settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

mcq/mcq/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('account.urls')),
    path('app/',include('app.urls')),
    path('dashboard/', include('app2.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mcq/app/models.py
from django.db import models
from autoslug import AutoSlugField
from account.models import User
from django.db.models.signals import pre_save,pre_delete
from django.dispatch import receiver


class Slider(models.Model):
    image = models.ImageField(upload_to='sliderimage/')
    text = models.CharField(max_length=150, null=True, blank=True)
    order_number = models.PositiveIntegerField()

    class Meta:
        verbose_name = "Slider"
        verbose_name_plural = "Sliders"
        ordering =['order_number']

    def __str__(self):
        return str(self.image.name)

class Categories(models.Model):
    categories_name = models.CharField(max_length=500)
    image = models.ImageField(upload_to='categoriesimage/')
    order_number = models.IntegerField()
    previous_price = models.IntegerField(null=True, blank=True)
    current_price = models.IntegerField()
    short_descriptions = models.TextField()
    categories_slug = AutoSlugField(populate_from='categories_name', unique=True, default=None)

    class Meta:
        verbose_name = "Question Bank"
        verbose_name_plural = "Question Bank's"
        ordering = ['-order_number']

    def __str__(self):
        return self.categories_name



@receiver(pre_delete, sender=Categories)
def prevent_category_deletion(sender, instance, **kwargs):
    if instance.question_sets.exists():
        raise models.ProtectedError(
            "Cannot delete this category because it has related question sets.",
            models.SET_NULL  
        )

payment_status =(
    ('paid','Paid'),
    ('pending','Pending')
)


class QuestionSets(models.Model):
    categorie = models.ForeignKey(Categories, on_delete=models.CASCADE, related_name='question_sets')
    set_name = models.CharField(max_length=300)
    order_number = models.IntegerField()
    is_free = models.BooleanField()
    questions_set_slug = AutoSlugField(populate_from='set_name', unique=True, default=None)

    
    class Meta:
        verbose_name = "Question Set"
        verbose_name_plural = "Question Sets"
        ordering = ['order_number']

    def __str__(self):
        return self.set_name

class Questions(models.Model):
    set_name = models.ForeignKey(QuestionSets, on_delete=models.CASCADE, related_name='question_set_name')
    question = models.CharField(max_length=300)
    file = models.ImageField(upload_to='file/',null=True, blank=True)
    question_slug = AutoSlugField(populate_from='question', unique=True, default=None)

    class Meta:
        verbose_name = "Question"
        verbose_name_plural = "Questions"
        ordering = ['-id']

    def __str__(self):
        return self.question

class Answer(models.Model):
    question = models.ForeignKey(Questions, on_delete=models.CASCADE, related_name='answers')
    answer = models.CharField(max_length=255)
    answerfile = models.ImageField(upload_to='answerimage/', null=True, blank=True)
    correct = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Answer"
        verbose_name_plural = "Answers"

    def __str__(self):
        return self.answer


class PaymentPatner(models.Model):
    name = models.CharField(max_length=150)
    qr_code = models.ImageField(upload_to='qr/')

    class Meta:
        ordering =['-id']

    def __str__(self):
        return self.name
    

class Purchases(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='users')
    sets = models.ForeignKey(QuestionSets, on_delete=models.CASCADE, related_name='questionset')
    payment_status = models.CharField(choices=payment_status, max_length=200, default='pending')
    payment_method = models.ForeignKey(PaymentPatner,on_delete=models.CASCADE, db_constraint=False, related_name='payment_method')
    payment_slip = models.ImageField(upload_to='paymentslip/')
    paid_amount = models.PositiveIntegerField()

    class Meta:
        verbose_name = "Purchase Question Set"
        verbose_name_plural = "Purchases Question Sets"
        ordering=['-id']

    def __str__(self):
        return f"{self.user.name} - {self.sets.set_name} ({self.payment_status})"



# score record
class Score(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_score')
    marks = models.PositiveIntegerField()
    attempt_date= models.DateField(auto_now_add=True)
    

    class Meta:
        verbose_name = "Score"
        verbose_name_plural ="Scores"

    def __str__(self):
        return self.user.name + str(self.marks)

   

mcq/app2/models.py
from django.db import models

# Create your models here.

mcq/app2/forms.py
from django import forms
from app.models import *
from ckeditor.fields import RichTextField
from ckeditor.widgets import CKEditorWidget
from ckeditor_uploader.widgets import CKEditorUploadingWidget


class CategoriesForm(forms.ModelForm):
    class Meta:
        model = Categories
        fields = '__all__'

class QuestionSetsForm(forms.ModelForm):
    class Meta:
        model = QuestionSets
        fields = '__all__'
        
class SliderForm(forms.ModelForm):
    class Meta:
        model = Slider
        fields = '__all__'
        
class QuestionsForm(forms.ModelForm):
    class Meta:
        model = Questions
        fields = '__all__'
        widgets = {
            'question': forms.TextInput(attrs={'class': 'form-control','placeholder':'Enter Question'})
        }

        
class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = '__all__'
        widgets = {
            'answer': forms.TextInput(attrs={'class': 'form-control','placeholder':'Enter Answer'})
        }




# class AnswerForm(forms.ModelForm):
#     class Meta:
#         model = Answer
#         fields = ['answer']

# AnswerFormSet = forms.inlineformset_factory(Questions, Answer, form=AnswerForm, extra=1, can_delete=True)

# class QuestionsForm(forms.ModelForm):
#     class Meta:
#         model = Questions
#         fields = ['set_name', 'question', 'image']
#         widgets = {
#             'set_name': forms.Select(attrs={'class': 'form-control'}),
#         }

mcq/app2/templates/app2/q2.html
{% extends 'app2/base.html' %}
{% load static %}
{% block title %} 
{% if instance %}Edit QuestionSets{% else %}Edit QuestionSets{% endif %}
{% endblock %}
{% block body %}

<title>{% if instance %}Edit QuestionSets{% else %}Edit QuestionSets{% endif %}
</title>

            <!-- ============================================================== -->
            <!-- Start Page Content here -->
            <!-- ============================================================== -->

            <div class="content-page">
                <div class="content">

                    <!-- Start Content-->
                    <div class="container-fluid">

                        <!-- start page title -->
                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box">
                                    <h4 class="page-title">{% if instance %}Edit QuestionSets{% else %}Add QuestionSets{% endif %}
                                    </h4>
                                </div>
                            </div>
                        </div>
                        <!-- end page title -->
                      
                        <form id="dynamicForm" action="{% url 'dashboard:add_question' %}" method="post" data-courses-url="{% url 'dashboard:ajax_load_courses' %}" >
                        {% csrf_token %}
                            <div class="mb-3">
                                <label for="{{ question_form.set_name.id_for_label }}" class="form-label" required>Set Name </label><br>
                                {{ question_form.set_name }}
                            </div>
                            {% comment %} <div class="mb-3">
                                <label for="{{ form.categorie.id_for_label }}" class="form-label">Main category </label>
                                <select id="add_question" name="categorie" style="width: 100%;">
                                    {% for categorie in main_categories %}
                                      <option value="{{ categorie.id }}" {% if categorie.id == form.initial.categorie.id %}selected{% endif %}>{{ categorie.categories_name }}</option>
                                    {% endfor %} 
                                  </select>
                                
                            </div>
                             {% endcomment %}
                            
                            {% comment %} <div class="mb-3">
                                <label  for="" class="form-label" required>Sub Category </label><br>
                                <select class="form-control"  id="courses" name="subcategory">
                                    <option value="" selected disabled>----Select Sub category----</option>
                                    <option value=""> </option>
                                    
                                </select>                                                       
                            </div>
             {% endcomment %}


                            <div class="mb-3">
                                <label for="{{ form.question.id_for_label }}" class="form-label">question </label>
                                <input type="text" name="question" id="{{ form.question.id_for_label }}" class="form-control" 
                                       value="{% if instance %}{{ instance.question }}{% endif %}" placeholder="Enter question">
                            </div>
        
                            <div class="mb-3 mt-3 mt-xl-0 " >
                                <label for="{{ form.image.id_for_label }}" class="form-label">Image:</label>
                                <input type="file" name="{{ form.image.name }}" id="{{ form.image.id_for_label }}" class=" img-fluid form-control custom-class" {% if not instance %}{% endif %} onchange="showPreview(this);">
                                <div id="imageContainer" style="width:auto">
                                    <img id="imagePreview" class="img-fluid" src="{% if instance %}{{ instance.image.url }}{% endif %}" alt="">
                                </div>
                            </div>
                            
                        </div> <!-- end col-->


                            <div id="inputContainer">
                                <!-- Dynamic input fields will be added here -->
                            </div>
                            <br>
                        <div class="d-flex">
                            <button type="button" onclick="addInput()" class="form-control">Add Answer</button>
                            <button type="button" onclick="removeInput()"class="form-control">Remove Last Answer Field</button>
                            <button type="submit" class="form-control">Submit</button>
                        </div>
                        </form>


                    </div> <!-- container -->

                </div> <!-- content -->
             

                <script>
                    let counter = 0;
                    const maxFields = 4;
                    const defaultFields = 2;
                  
                    // Add default fields
                    for (let i = 0; i < defaultFields; i++) {
                        addInput();
                    }
                  
                    function addInput() {
                        if (counter < maxFields) {
                            counter++;
                            const inputContainer = document.getElementById('inputContainer');
                  
                            const inputGroup = document.createElement('div');
                            inputGroup.classList.add('input-group', 'pt-3', 'required');
                  
                            const inputField = document.createElement('input');
                            inputField.type = 'text';
                            inputField.name = `answers_${counter}`;
                            inputField.placeholder = `Answer ${counter}`;
                            inputField.classList.add('form-control');
                  
                            const imageField = document.createElement('input');
                            imageField.type = 'file';
                            imageField.name = `imageField_${counter}`;
                            imageField.accept = 'image/*';
                            imageField.classList.add('form-control');
                  
                            const radioGroup = document.createElement('div');
                            radioGroup.classList.add('form-check');
                  
                            const radioLabel = document.createElement('label');
                            radioLabel.classList.add('form-check-label');
                  
                            const radioInput = document.createElement('input');
                            radioInput.type = 'radio';
                            radioInput.name = 'radioGroup';
                            radioInput.value = `radioOption_${counter}`;
                            radioInput.classList.add('form-check-input');
                  
                            radioLabel.appendChild(radioInput);
                            radioLabel.appendChild(document.createTextNode('Select Correct Answer'));
                  
                            radioGroup.appendChild(radioLabel);
                  
                            inputGroup.appendChild(inputField);
                            inputGroup.appendChild(imageField);
                            inputGroup.appendChild(radioGroup);
                  
                            inputContainer.appendChild(inputGroup);
                        } else {
                            alert('Maximum 4 fields reached!');
                        }
                    }
                  
                    function removeInput() {
                        const inputContainer = document.getElementById('inputContainer');
                        const inputGroups = inputContainer.getElementsByClassName('input-group');
                  
                        if (inputGroups.length > defaultFields) {
                            inputContainer.removeChild(inputGroups[inputGroups.length - 1]);
                            counter--;
                        }
                    }
                
                    /*function sendData() {
                        const dynamicData = [];
                
                        for (let i = 1; i <= counter; i++) {
                            const answerField = $(`input[name="answers_${i}"]`).val();
                            const imageField = $(`input[name="imageField_${i}"]`)[0].files[0];
                            const isCorrect = $(`input[name="radioOption_${i}"]:checked`).val() === `radioOption_${i}`;
                
                            dynamicData.push({ answer: answerField, image: imageField, isCorrect: isCorrect });
                            console.log(`Answer ${i}:`, answerField);
                            console.log(`Image ${i}:`, imageField);
                            console.log(`Is Correct ${i}:`, isCorrect);
                        }
                        

                        console.log(dynamicData)
                        // Additional data from your form
                        const set_name = $('#id_set_name').val();
                        const question = $('#id_question').val();
                        const image = $('#id_image')[0].files[0];
                
                        // Send data to Django view using AJAX
                      $.ajax({
                            type: 'POST',
                            url: '{% url "dashboard:add_question" %}', 
                            data: {
                                csrfmiddlewaretoken: '{{ csrf_token }}',
                                set_name: set_name,
                                question: question,
                                image: image,
                                dynamic_data: JSON.stringify(dynamicData)
                            },
                            success: function (response) {
                                console.log(response);
                            },
                            error: function (error) {
                                console.error(error);
                            }
                        });
                    }*/
                </script>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>

                <script>
                    $(document).ready(function() {
                        $("#category").change(function() {
                            var url = $("#form").attr("data-courses-url");
                            var programmingId = $(this).val();
                            console.log(programmingId);
                            $.ajax({
                                url: url,
                                data: {
                                    'programming': programmingId
                                },
                                success: function(data) {
                                    $("#courses").html(data);
                                    //console.log(data);
                                },
                                error:function(data){
                                    console.log(data);
                                }
                            });
                        });
                    });
                </script>
                  
       {%endblock%}

mcq/app2/templates/app2/test.html
{% extends 'app2/base.html' %}
{% load static %}
{% block title %} 
{% if instance %}Edit QuestionSets{% else %}Edit QuestionSets{% endif %}
{% endblock %}
{% block body %}

<title>{% if instance %}Edit QuestionSets{% else %}Edit QuestionSets{% endif %}
</title>


            <!-- ============================================================== -->
            <!-- Start Page Content here -->
            <!-- ============================================================== -->

            <div class="content-page">
                <div class="content">

                    <!-- Start Content-->
                    <div class="container">

                        <!-- start page title -->
                        <div class="row">
                            <div class="col-12">
                                <div class="page-title-box">
                                    <h4 class="page-title">{% if instance %}Edit QuestionSets{% else %}Add QuestionSets{% endif %}
                                    </h4>
                                </div>
                            </div>
                        </div>
                        <!-- end page title -->
                        {% if messages %}
                            {% for msg in messages %}
                                <div class="alert alert-{{ msg.tags }} alert-dismissible text-bg-{{ msg.tags }} border-0 fade show" role="alert">
                                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="alert" aria-label="Close"></button>
                                    <strong>{% if msg.tags == 'success' %}Success{% elif msg.tags == 'warning' %}Warning{% endif %} - </strong>{{ msg.message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                        
                        <form  id="dynamicForm" action="{% url 'dashboard:test' %}" method="post"  enctype="multipart/form-data" >


                        {% csrf_token %}
                        

                        <div class="row">
                            <input type="hidden" name="set_name" id="set_id" value="{{set_name}}">
                            <div class="col-md-6">
                                <div class="mb-3">
                                    <label for="id_question" class="form-label">Question</label><br>
                                    {{ form.question }}
                                </div>
                            </div>
                            <div class="col-md-6">

                                <div class="mb-3">
                                    <label for="id_set_name"  class="form-label">File</label><br>
                                    <input type="file" name="file" class="form-control">
                                </div>
                            </div>
                            
                            
                        </div>

                        <div class="row">
                            {% for i in loop_times %}
                                <div class="col-md-5">
                                    <div class="mb-3">
                                        <label for="id_question" class="form-label">Answer</label><br>
                                        <input type="text" required name="{{answer_forms.answer.name}}_{{i}}" class="form-control" placeholder="Enter Answer.">
                                    </div>
                                </div>
                                <div class="col-md-5">
                                    <div class="mb-3">
                                        <label for="id_set_name"  class="form-label">File</label><br>
                                        <input type="file" name="{{ answer_forms.answerfile.name }}_{{i}}" class="form-control">
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="mb-3">
                                        <label for="id_set_name"  class="form-label">Is Correct</label><br>
                                        <input type="checkbox" name="{{answer_forms.correct.name}}_{{i}}" >
                                        
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        

                  

                        <div class="row">
                        <div class="col-4">
                            {% comment %} <button type="button" id="addAnotherField" class="btn btn-danger chat-send waves-effect waves-light">Save and Add Another</button> {% endcomment %}

                                <button type="submit" class="btn btn-danger chat-send waves-effect waves-light">Save and Add Another</button>

                                </div>
                            </div>
                        </div>
                
                        </form>


                    </div> <!-- container -->

                </div> <!-- content -->
             

                
                <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.7.2/dist/js/bootstrap.bundle.min.js"></script>
                <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
                
                <script>
                    $(document).ready(function() {
                        // Set up event listener for the change in the category dropdown
                        $('#id_categorie').change(function() {
                            var categoryId = $(this).val();
                            // Make an AJAX request to get question sets for the selected category
                            $.ajax({
                                url: "{% url 'dashboard:get_question_sets' %}",  // Replace with the URL to your view
                                data: {'category_id': categoryId},
                                dataType: 'json',
                                success: function(data) {
                                    // Update the options in the question set dropdown
                                    var questionSetDropdown = $('#id_set_name');
                                    questionSetDropdown.empty();
                                    $.each(data, function(key, value) {
                                        questionSetDropdown.append($('<option></option>').attr('value', value.id).text(value.set_name));
                                    });
                                }
                            });
                        });
                    });


{% comment %} 
                    $('#dynamicForm').submit(function (e) {
                        e.preventDefault(); // Prevent the form from submitting traditionally
            
                        // Make an AJAX request to submit the form data
                        $.ajax({
                            type: $(this).attr('method'),
                            url: $(this).attr('action'),
                            data: new FormData(this),
                            processData: false,
                            contentType: false,
                            success: function (data) {
                                // Handle the success response
                                console.log(data);
                                // Optionally, you can update the UI or perform other actions
                            },
                            error: function (error) {
                                // Handle the error response
                                console.error(error);
                                // Optionally, you can update the UI or perform other actions
                            }
                        });
                    }); {% endcomment %}

                </script>
                  
       {%endblock%}